name = "sales-team"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "sales_db"
database_name = "sales-admin-db"
database_id = "eb493199-dd34-4f5a-8142-be488f9c51ec"
